### PR TITLE
OSC-Theme based site

### PR DESCRIPTION
**Pull request by khos2ow**

### CODE REVIEW

**Comment by khos2ow** [comment]
@RichardLitt @SuriyaaKudoIsc we're good to go.

**Comment by RichardLitt** [comment]
Cool. Up to @SuriyaaKudoIsc whether he wants this to be merged; each chapter should be allowed to have their own styles, I think. :)

**Review by suriyaa — APPROVED** [review]
@khos2ow :+1: LGTM. Thanks.

**Comment by suriyaa** [comment]
🏙 Beautiful website:

[screenshot_2018-06-20 open source cities - munich](https://opensourcecities.github.io/munich/)

**Pull request merged**
